import "../styles/globals.css";
import { AppProps } from "next/app";
import Head from "next/head";
import Layout from "components/layout";

const App = ({ Component, pageProps }: AppProps) => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <Component {...pageProps} />
    </Layout>
  </>
);

export default App;
